export const POST_REGISTER_REQUEST: 'POST_REGISTER_REQUEST' = 'POST_REGISTER_REQUEST';
export const POST_REGISTER_FAILED: 'POST_REGISTER_FAILED' = 'POST_REGISTER_FAILED';
export const POST_REGISTER_SUCCESS: 'POST_REGISTER_SUCCESS' = 'POST_REGISTER_SUCCESS';

export const POST_FORGOT_PASSWORD_REQUEST: 'POST_FORGOT_PASSWORD_REQUEST' ='POST_FORGOT_PASSWORD_REQUEST';
export const POST_FORGOT_PASSWORD_SUCCESS: 'POST_FORGOT_PASSWORD_SUCCESS' ='POST_FORGOT_PASSWORD_SUCCESS';
export const POST_FORGOT_PASSWORD_FAILED: 'POST_FORGOT_PASSWORD_FAILED' ='POST_FORGOT_PASSWORD_FAILED';

export const POST_RESET_PASSWORD_REQUEST: 'POST_RESET_PASSWORD_REQUEST' ='POST_RESET_PASSWORD_REQUEST';
export const POST_RESET_PASSWORD_SUCCESS: 'POST_RESET_PASSWORD_SUCCESS' ='POST_RESET_PASSWORD_SUCCESS';
export const POST_RESET_PASSWORD_FAILED: 'POST_RESET_PASSWORD_FAILED' ='POST_RESET_PASSWORD_FAILED';

export const POST_AUTHORIZATION_REQUEST: 'POST_AUTHORIZATION_REQUEST' = 'POST_AUTHORIZATION_REQUEST';
export const POST_AUTHORIZATION_FAILED: 'POST_AUTHORIZATION_FAILED' = 'POST_AUTHORIZATION_FAILED';
export const POST_AUTHORIZATION_SUCCESS: 'POST_AUTHORIZATION_SUCCESS' = 'POST_AUTHORIZATION_SUCCESS';

export const GET_USER_REQUEST: 'GET_USER_REQUEST' = 'GET_USER_REQUEST';
export const GET_USER_FAILED: 'GET_USER_FAILED' = 'GET_USER_FAILED';
export const GET_USER_SUCCESS: 'GET_USER_SUCCESS' = 'GET_USER_SUCCESS';

export const UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST' = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS' = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILED: 'UPDATE_USER_FAILED' = 'UPDATE_USER_FAILED';

export const POST_REFRESH_TOKEN_REQUEST: 'POST_REFRESH_TOKEN_REQUEST' = 'POST_REFRESH_TOKEN_REQUEST';
export const POST_REFRESH_TOKEN_SUCCESS: 'POST_REFRESH_TOKEN_SUCCESS' = 'POST_REFRESH_TOKEN_SUCCESS';
export const POST_REFRESH_TOKEN_FAILED: 'POST_REFRESH_TOKEN_FAILED' = 'POST_REFRESH_TOKEN_FAILED';

export const POST_LOGOUT_USER_REQUEST: 'POST_LOGOUT_USER_REQUEST' = 'POST_LOGOUT_USER_REQUEST';
export const POST_LOGOUT_USER_SUCCESS: 'POST_LOGOUT_USER' = 'POST_LOGOUT_USER';
export const POST_LOGOUT_USER_FAILED: 'POST_LOGOUT_USER_FAILED' = 'POST_LOGOUT_USER_FAILED';